[build]
builder = "DOCKERFILE"
dockerfilePath = "ocr/Dockerfile"

[deploy]
startCommand = "python -m plaiflow_ocr.api"
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
